import { AuthProvider } from "@/app/Providers";

import "@/app/globals.css";
export const metadata = {
  title: `Mike's Friendly Poker`,
  description: 'Generated by Next.js',
  'apple-mobile-web-app-capable': 'yes',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <link rel="manifest" href="manifest.json" />
      <body>
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  )
}
